### ISSUE TITLE
Sign restrictions

### ISSUE THREAD

**Issue by opalmen** [naffe15/BVAR_#12]
There seems to be an issue with estimating the model using sign restrictions (Matlab R2022b):

Unrecognized function or variable 'maxhorsign'.

Error in iresponse_sign (line 51)
hor0 = maxhorsign(signrestriction) ;

Error in bvar_ (line 951)
        [irsign,Omega]         = iresponse_sign(Phi(1 : ny*lags, 1 : ny),Sigma,hor,signs);

**Comment by naffe15** [comment]
the function 'maxhorsign' was indeed missing and has been added. the identification with sign restrictions should work now.
f.

**Comment by opalmen** [comment]
I can confirm that it is working now. Thank you!
