### ISSUE TITLE
Toolbox requirements

### ISSUE THREAD

**Issue by Wjgatt** [naffe15/BVAR_#13]
Perhaps it would be helpful to inform potential users that the toolbox requires Matlab's Statistics and Machine Learning Toolbox to run, at least definitely to run the 'direct methods' routines.

**Comment by naffe15** [comment]
Hi, thanks for using the toolbox and for flagging this. the statistical_toolbox is indeed required and the optimization_toolbox if optimizer other than Sims are used. I have added this info in the README file
best
f.

**Comment by Wjgatt** [comment]
Thanks, and thanks for a great toolbox!
