### ISSUE TITLE
function "polydet_break" missing?

### ISSUE THREAD

**Issue by sergiohrs** [naffe15/BVAR_#14]
Hello! The hitchhiker’s guide mentions a function "polydet_break" in page 119, but I couldn't find it in the "bvartools" folder. Is it missing? 

Thanks! Best, Sergio

**Comment by naffe15** [comment]
Thanks Sergio for flagging the missing function and apologies for the late reply. I have uploaded the function you requested. 
best
f.

**Comment by sergiohrs** [comment]
Thanks!
