### ISSUE TITLE
Error when generating forecasts conditional on 2+ variables 

### ISSUE THREAD

**Issue by devproglab** [naffe15/BVAR_#15]
I have tried to use the following code to generate the forecast conditional on the values of the 1st and the 4th endogenous variables:
```
options.max_minn_hyper = 1;
options.endo_index = [1, 4];
options.exo_index = [1, 4];
options.endo_path = [3 3 3 3 3 3 3 3; 45 50 50 50 50 50 50 50]';
c.var(1) = bvar_(y,lags,options);
```
However, what I obtain is an error message:
```
Error using cforecasts2
something went wrong: the number of path and the number of vars are not consistent.
Error in bvar_ (line 1013)
            cforecasts2(endo_path,endo_path_index,exo_index,forecast_data,Phi,Sigma,Omega);
```
It seems to mee that [here](https://github.com/naffe15/BVAR_/blob/6ae839c31981bbd551b7dea44e79e15f11ab200e/bvartools/cforecasts2.m#L44) the correct line should be:
`if Ncondvar ~= length(endo_index)
`
rather than
`if size(Ncondvar,2) ~= length(endo_index)
`
When I manually change it, the code still throws an error:
`Incorrect dimensions for matrix multiplication. Check that the number of columns in the first matrix matches the number of rows in the second matrix. To
operate on each element of the matrix individually, use TIMES (.*) for elementwise multiplication.
Error in cforecasts2 (line 95)
    e(:,t) = inv(RR(endo_index,exo_index))*(endo_path(t,:) - y(endo_index));
`
What am I missing?

**Comment by devproglab** [comment]
> Thanks for spotting these errors. there were a couple of bugs which have been fixed. the conditional forecasts with multiple endogenous paths should work now.
> 
> I tested the codes with your example and by imposing the path on R and M3 as follows options.endo_index = [4 5]; options.endo_path = [Euribor1Y(in_sample_end+1:end) M3(in_sample_end+1:end)]; it works both when using all shock and when using only the recursive identified ones (i.e. options.exo_index = options.endo_index;)
> 
> let me know if you have issues.

It works now, thanks a lot!

(Unrelated to this issue) I was wondering if it is possible (and if so, how difficult it could be) to implement steady-state priors in the spirit of Villani (2009) (https://www.jstor.org/stable/40206295) within the toolbox?

**Comment by naffe15** [comment]
If you are not interested in the VECM form, you just need to specify a prior for the deterministic trend/exogenous. 

In the codes, the AR parameters and the deterministic trend/exogenous parameters are bundled together in the Phi matrix, the order is AR1, .. ARp, constant and exogenous variables (trends, breaks ...). You just need to specify the appropriate prior for each parameter. Notice that the Minnesota dummy prior does not work in this context; but you can set up a Minnesota prior for the AR1 and lags. I hope this helps
