### ISSUE TITLE
Proxy and sign restriction

### ISSUE THREAD

**Issue by NicoGreggio** [naffe15/BVAR_#19]
Dear Professor Ferroni, 
I wanted to know if one could through the empirical macro toolbox estimate a shock by applying a mixture of proxy instrument and sign restriction. It seems to me that the Ambrogio Cesa-Bianchi toolbox allows identifications of that kind but I don't see a way to do it in your toolbox, probably due to my ignorance. 
I thank in advance

**Comment by naffe15** [comment]
Hi Nicolò 

Thanks for pointing this out. To make sure I understand you are referring to the identification of multiple shocks some with instruments and some others with signs. If this is the case, the short answer is no at the moment. 

However, with a couple of lines of code you can implement this. In the output of the bvar_ you have the 3 dimensional array BVAR.Omegap which contains K draws of the rotation matrix where only the first shock is identified (with the instrument). Basically you need to rotate the other dimensions of the BVAR.Omegap(:,:,d) matrix. 

Assume that you have one shock identified with instrument and one with sign restrictions. And the size of the VAR is n. 

You can do the following 
- draw and orthonormal rotation of size n-1 with generateQ.m, call it Qzero. 
- define 
Q = [1, zeros(1,n-1); zeros(n-1,1), Qzero]
- define
OmegaQ = BVAR.Omegap(:,:,d) * Q;
This rotation leaves the first column of BVAR.Omegap(:,:,d) unchanged and rotate all other dimensions. 
- compute irf with 
y =  iresponse(BVAR.Phi(:,:,d), BVAR.Sigma(:,:,d),hor0,OmegaQ);
- check sign restrictions with 
  [flag,fsign] = checkrestrictions2(signrestriction,y);

If flag=1, stop. Else try another draw. 

Do this for all the BVAR.Omegap(:,:,d). 

I hope this helps.

**Comment by NicoGreggio** [comment]
Thank you very much professor for your answer but my doubt is slightly different. 
I am trying to estimate the effect of oil supply shocks on some European variables starting from 2000 using the Kanzig's instrument (2021). Since the small sample I lose some key observations and due to that I get inconsistent responses (in particular for the production index). Therefore I wanted to strengthen the approach of my identification by applying on the same oil price shock identify using the proxy also a sign restriction on the reaction of the production index. I gather from your response that this should be done with an ad hoc loop discarding those Omegap(:,:,1) draws that satisfy the condition. 
Does this sound correct to you? 
Thanks again for your reply and the wonderful package
Nicolò

**Comment by naffe15** [comment]
Nope, that's not what I meant. My understanding of the proxy identification tells me that the proxy/IV approach delivers point identification of the shock up to a sign normalization; so no sign restrictions can be imposed in combination with IV on the same shock. sign restrictions can be imposed on the other shocks of the system.

**Comment by NicoGreggio** [comment]
I was reading obout it in this paper: https://www.bankofengland.co.uk/-/media/boe/files/working-paper/2022/identification-of-svar-models-by-combining-sign-restrictions-with-external-instruments.pdf
Maybe i misunderstand the meaning of the paper.

**Comment by naffe15** [comment]
Thanks for the reference. Now I understand. Unlike the case with one shock to identify with instruments, additional restrictions can be imposed when interested in identifying multiple shocks with multiple instruments.  
The toolbox only allows to estimate one structural shock with instruments.
