### ISSUE TITLE
Are the line 863&864  var.X and Var.y rigint in bvar.m?

### ISSUE THREAD

**Issue by astonetiger** [naffe15/BVAR_#7]
When I run any example, it alarms "Unable to resolve the name var.X." in bvar.m. I've checked there is no var in any places, so I modify it to varols.X, and var.y to varols.y.  

Please help check if it is right.

Thank you!

**Comment by naffe15** [comment]
My version of matlab (2017b) recognizes 'var' as a non-local variable. Hence, when calling 'posterior.m' I do not need to specify 'var' as output.  To avoid crashes with different matlab versions, I modified 'posterior.m' to have 'var' as output (lines 599 and 927 in bvar.m). Thanks for spotting this.
